# This is the core app definition.
# It contains settings which apply across all environments.
version: '3.7'

services:

  todo-web:
    image: diamol/ch06-todo-list
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat