version: "3.7"

services:
  numbers-api:
    image: diamol/ch08-numbers-api:v3
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 5s

  numbers-web:
    image: diamol/ch08-numbers-web:v3
    healthcheck:
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s
